---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy to dev
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      echo appName "${CF_APP}"
      serviceId=`echo ${CF_APP} | awk '{print substr($0, 12)}'`
      echo serviceId "${serviceId}"
      serviceJson=`cf curl /v2/service_instances/${serviceId}`
      echo serviceJson "${serviceJson}"
      errorCode=`echo ${serviceJson} | grep -Po '(?<="error_code": ")[^"]*' || true` 
      echo errorCode ${errorCode}
      if [[ -z $errorCode ]]
      then
       serviceName=`echo ${serviceJson} | grep -Po '(?<="name": ")[^"]*' || true`
       echo serviceName "${serviceName}"
       if [[ ! -z $serviceName ]]
       then
        sed -i '$ a \  services:' manifest.yml
        sed -i "$ a \  - ${serviceName}" manifest.yml
       else
         echo "The problem occured when retrieving the serviceName. The service will not be bind to the app."
       fi 
      else
        echo "The problem occured when retrieving the serviceName. The service will not be bind to the app."
      fi
      echo manifest.yml
      cat manifest.yml
      cf push "${CF_APP}"
      # View logs
      #cf logs "${CF_APP}" --recent
